### ISSUE TITLE
Cycle detected when installing from master on github

### ISSUE THREAD

**Issue by mansona** [ef4/prember#13]
Howdy, me again 👋 

I'm just trying to start the work for https://github.com/ef4/prember/issues/12#issuecomment-361305940 and I'm hitting an issue that I thought was something to do with npm link but I don't think it is on further reflection...

I did the following steps: 
```
➜  deprecation-app git:(master) ✗ npm i ef4/prember
+ prember@0.3.0-alpha.1
added 5 packages in 10.186s
➜  deprecation-app git:(master) ✗ ember build -e production
cycle detected: prember <- ember-cli-fastboot <- broccoli-asset-rev <- prember
```
and as you see it's complaining about a cycle. I have no idea what is going on here because I've never seen something like this before 🤔 

This is working on the new ember deprecations app so if you want to try it out you can clone the repo and try the above steps: https://github.com/ember-learn/deprecation-app

I'm going to continue my experiment with the static file serving on a fork of the `v0.2.2` tag 👍

**Comment by ef4** [comment]
The master branch (and alpha releases) depend on unreleased changes to
other projects. See the git dependencies in package.json.

**Comment by mansona** [comment]
cool thanks @ef4 👍 I figured it was something to do with that

**Comment by mansona** [comment]
Hi 👋me again! 

I've just tried prember@0.3.0-alpha.3 and I still got the issue: 

```cycle detected: prember <- ember-cli-fastboot <- broccoli-asset-rev <- prember```

I'm not trying to rush you or anything, we're happy to continue using the branch for #15 in the meantime but if you want a test case to see if the issue is solved I'm your man 😂let me know if there is anything I can do to help 👍

**Comment by ef4** [comment]
You can get around the cycle problem if you use these dependencies:

    "broccoli-asset-rev": "https://github.com/ef4/broccoli-asset-rev#838f1b7186fde566d3e8010196c1f974423a4946",
    "ember-cli-fastboot": "https://github.com/ef4/ember-cli-fastboot#48b94151e373bc33bcc3ad737a1e3e2a7e4ed8da",

The need for these is why we're still on an alpha release.  I hope we can get a fix merged upstream.

**Comment by mansona** [comment]
So it's still not quite working 🤔 I've created a branch on deprecations-app to test out your suggestions and as a potential test-bed for this setup: https://github.com/ember-learn/deprecation-app/pull/72. If we're just at a stage where it's not even ready to be tested like this please just tell me to back off and I'll keep track of the upstream dependencies and we'll revisit this later 😂

For the broccoli-asset-rev change, I'm assuming that's related to this PR: https://github.com/rickharrison/broccoli-asset-rev/pull/125? I'm only asking because the SHAs don't match 🤔 

Same question for https://github.com/ember-fastboot/ember-cli-fastboot/pull/546, is that the related PR? I'm just asking because I want to keep track of the right things. 

By the way... this is some awesome work you're doing 😍

**Comment by mansona** [comment]
You will probably see that the deprecations-app PR is now failing on Travis. When running this locally it gives this error: 

```
ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Path must be a string. Received undefined
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Path must be a string. Received undefined
  - name: TypeError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:1239:7)
    at _migrateAddonInitializers (/Users/mansona/git/stonecircle/opensource/ember-guides/deprecation-app/node_modules/ember-cli-fastboot/lib/build-utilities/migrate-initializers.js:92:32)
    at migrateInitializers (/Users/mansona/git/stonecircle/opensource/ember-guides/deprecation-app/node_modules/ember-cli-fastboot/lib/build-utilities/migrate-initializers.js:121:3)
    at Class.included (/Users/mansona/git/stonecircle/opensource/ember-guides/deprecation-app/node_modules/ember-cli-fastboot/index.js:64:5)
    at project.addons.project.addons.filter.addon (/Users/mansona/git/stonecircle/opensource/ember-guides/deprecation-app/node_modules/ember-cli/lib/broccoli/ember-app.js:538:17)
    at Array.filter (<anonymous>)
    at EmberApp._notifyAddonIncluded (/Users/mansona/git/stonecircle/opensource/ember-guides/deprecation-app/node_modules/ember-cli/lib/broccoli/ember-app.js:535:47)
    at new EmberApp (/Users/mansona/git/stonecircle/opensource/ember-guides/deprecation-app/node_modules/ember-cli/lib/broccoli/ember-app.js:164:10)
    at module.exports (/Users/mansona/git/stonecircle/opensource/ember-guides/deprecation-app/ember-cli-build.js:20:13)
```

let me know if any of this is helpful

**Comment by mansona** [comment]
so this was solved a long long time ago 😂 thanks for doing all the hard work to get this solved 🎉
